name: pixlog_challenge
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.2
  hive: ^2.2.2
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_test: ^1.0.1
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
